spring.application.name=api

spring.datasource.url=jdbc:mysql://localhost:3306/vollmed_api
spring.datasource.username=root
spring.datasource.password=Mdgvl2811*

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.error.include-message=always

api.security.token.secret=${JWT_SECRET:12345678}